spring:
  application:
    name: dnrush-plus-website
  
  # Jackson配置
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  
  # 資料庫配置 (使用 MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/dnrush_plus?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: karter
    password: seal1127
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 只更新結構，不刪除數據
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never  # 改為 never，這樣不會每次啟動都執行 SQL 初始化腳本
      continue-on-error: true  # 如果數據已存在，忽略錯誤
  
  # Thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  # 靜態資源配置
  web:
    resources:
      static-locations: classpath:/static/
  
  # 檔案上傳配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 伺服器配置
server:
  port: 8080
  servlet:
    context-path: /

# 日誌配置
logging:
  level:
    com.dnrush: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 自定義配置
app:
  upload:
    path: uploads/
  image:
    base64:
      prefix: data:image/jpeg;base64,
